services:
  - name: dynamic Webserver
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabse: 
          name: fandago_score_comprassions
          property: host