services:
  - name: dynamic Webserver
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: fandango_score_comparssions
          properties: host